plugins {
    id 'multiloader-common'
    id 'net.fabricmc.fabric-loom'
}

configurations {
    commonJava {
        canBeResolved = true
    }
    commonResources {
        canBeResolved = true
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"
    implementation project(':fabric')

    compileOnly(project(':common')) {
        def loaderAttribute = Attribute.of('io.github.mcgradleconventions.loader', String)
        attributes {
            attribute(loaderAttribute, 'common')
        }
    }
    compileOnly(project(':testmod-common')) {
        def loaderAttribute = Attribute.of('io.github.mcgradleconventions.loader', String)
        attributes {
            attribute(loaderAttribute, 'common')
        }
    }
    commonJava project(path: ':testmod-common', configuration: 'commonJava')
    commonResources project(path: ':testmod-common', configuration: 'commonResources')
}

tasks.named('compileJava', JavaCompile) {
    dependsOn(configurations.commonJava)
    source(configurations.commonJava)
}

processResources {
    dependsOn(configurations.commonResources)
    from(configurations.commonResources)
}

tasks.named('javadoc', Javadoc).configure {
    dependsOn(configurations.commonJava)
    source(configurations.commonJava)
}

tasks.named('sourcesJar', Jar) {
    dependsOn(configurations.commonJava)
    from(configurations.commonJava)
    dependsOn(configurations.commonResources)
    from(configurations.commonResources)
}

loom {
    runs {
        client {
            client()
            setConfigName('Fabric Testmod Client')
            ideConfigGenerated(true)
            runDir('runs/client')
            if (project.hasProperty('withoutOptionalPackets')) {
                property 'testmod.optionalPackets.disabled', 'true'
            }
        }
        server {
            server()
            setConfigName('Fabric Testmod Server')
            ideConfigGenerated(true)
            runDir('runs/server')
        }
        datagen {
            client()
            setConfigName('Fabric Testmod Datagen')
            ideConfigGenerated(true)
            runDir('runs/datagen')
            property "fabric-api.datagen"
            property "fabric-api.datagen.modid", "testmod"
            property "fabric-api.datagen.output-dir", file("src/generated/resources").absolutePath
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

def loaderAttribute = Attribute.of('io.github.mcgradleconventions.loader', String)
['apiElements', 'runtimeElements', 'sourcesElements', 'javadocElements', 'includeInternal', 'modCompileClasspath'].each { variant ->
    configurations.named("$variant") {
        attributes {
            attribute(loaderAttribute, 'fabric')
        }
    }
}
sourceSets.configureEach {
    [it.compileClasspathConfigurationName, it.runtimeClasspathConfigurationName].each { variant ->
        configurations.named("$variant") {
            attributes {
                attribute(loaderAttribute, 'fabric')
            }
        }
    }
}
