org.gradle.jvmargs=-Xmx6G
org.gradle.daemon=false

minecraft_version=1.21.9

platforms=fabric,neoforge

archives_base_name=polylib
mod_version=2109.1.0
maven_group=net.creeperhost
curseforge_id=576589
artifact_type=release
modrinth_id=6lvkzFFj

architectury_version=18.0.2

fabric_loader_version=0.17.2
fabric_api_version=0.133.14+1.21.9

neoforge_version=21.9.16-beta

jei_version=19.5.3.67
