package net.creeperhost.polylib.event;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.function.Function;

/**
 * Lightweight event container used by PolyLib's cross-loader event API.
 * <p>
 * Each event stores registered handlers and exposes a combined invoker generated by
 * the supplied combiner. Event holder classes define the combiner behavior for each
 * event, including whether listeners are all called, whether a boolean result is
 * aggregated, or whether a {@code CancelContext} short-circuits dispatch.
 *
 * @param <T> the functional callback type registered to this event
 */
public final class PolyEvent<T>
{

    private final List<T> handlers = new ArrayList<>();
    private final Function<List<T>, T> combiner;
    private T invoker;

    private PolyEvent(Function<List<T>, T> combiner)
    {
        this.combiner = combiner;
        this.invoker = combiner.apply(Collections.emptyList());
    }

    /**
     * Creates an event with the supplied handler combiner.
     *
     * @param combiner function that turns the current handler list into an invoker
     * @param <T>      the callback type
     * @return a new event
     */
    public static <T> PolyEvent<T> create(Function<List<T>, T> combiner)
    {
        return new PolyEvent<>(combiner);
    }

    /**
     * Registers a handler and rebuilds this event's invoker.
     *
     * @param handler the callback to add
     */
    public void register(T handler)
    {
        handlers.add(handler);
        invoker = combiner.apply(Collections.unmodifiableList(handlers));
    }

    /**
     * @return the combined callback used to fire this event
     */
    public T invoker()
    {
        return invoker;
    }
}
