modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/CreeperHost/PolyLib/issues"
license = "BSD 4-Clause License"

[[mods]]
modId = "polylib"
version = "${version}"
displayName = "PolyLib"
authors = "CreeperHost"
description = '''"PolyLib," developed by CreeperHost Ltd.,
is a compact Minecraft library mod focused on providing a collection of helper classes.
These classes are designed to simplify various aspects of mod development, offering tools for easier GUI creation and other development enhancements to improve efficiency and user experience.
'''
logoFile="polylib_logo.png"


[[dependencies.polylib]]
modId = "neoforge"
type="required"
versionRange = "[20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.polylib]]
modId = "minecraft"
type="required"
versionRange = "[1.20.6,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.polylib]]
modId = "architectury"
type="required"
versionRange = "[12.0.27,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "polylib-neoforge.mixins.json"

[[mixins]]
config = "polylib.mixins.json"
