modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/CreeperHost/PolyLib/issues"
license = "Insert License Here"

[[mods]]
modId = "testmod"
version = "1.0.0"
displayName = "TestMod"
authors = "CreeperHost"
description = '''
'''

[[dependencies.testmod]]
modId="polylib"
type="required"
# This version range declares a minimum of the current minecraft version up to but not including the next major version
versionRange="*"
ordering="AFTER"
side="BOTH"