packages:
  - .

onlyBuiltDependencies:
  - esbuild
  - sharp

minimumReleaseAgeExclude:
  - '@astrojs/markdown-satteri'
  - '@astrojs/starlight'
  - astro

allowBuilds:
  esbuild: true
  sharp: true
