name: Java CI

on:
  push:
    branches: [ 1.19, 1.19.3, 1.20 ]
  workflow_dispatch:
    inputs:
      norelease:
        description: 'Do not publish'
        required: true
        default: 'false'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    if: |
      !contains(github.event.head_commit.message, '[ciskip]')
    steps:
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build with Gradle
        env:
          CREEPERHOST_MAVEN_TOKEN: ${{ secrets.CREEPERHOST_MAVEN_TOKEN}}
        run: |
          chmod +x ./gradlew
          ./gradlew build publish --stacktrace --no-daemon
      - name: Send Forge notification to Discord
        uses: sebastianpopp/discord-action@releases/v2
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          message: https://maven.creeperhost.net/net/creeperhost/polylib-forge/1200.0.0-build.${{github.run_number}}/polylib-forge-1200.0.0-build.${{github.run_number}}.jar
      - name: Send Fabric notification to Discord
        uses: sebastianpopp/discord-action@releases/v2
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          message: https://maven.creeperhost.net/net/creeperhost/polylib-fabric/1200.0.0-build.${{github.run_number}}/polylib-fabric-1200.0.0-build.${{github.run_number}}.jar
